# Generated by Django 6.0.7 on 2026-07-28 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('travelers', models.PositiveIntegerField(default=1)),
                ('travel_style', models.CharField(choices=[('Adventure', 'Adventure'), ('Relaxation', 'Relaxation'), ('Luxury', 'Luxury'), ('Budget', 'Budget'), ('Culture', 'Culture')], default='Adventure', max_length=50)),
                ('itinerary', models.JSONField(blank=True, null=True)),
                ('trip_image', models.ImageField(blank=True, null=True, upload_to='trips/')),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
