# Generated by Django 6.0.1 on 2026-08-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='is_favorite',
            new_name='favorite',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='trip_image',
        ),
        migrations.AddField(
            model_name='trip',
            name='packing_list',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='trip',
            name='budget',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trip',
            name='itinerary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='trip',
            name='travel_style',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='trip',
            name='travelers',
            field=models.IntegerField(default=1),
        ),
    ]
