# Generated by Django 6.0.1 on 2026-08-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_rename_is_favorite_trip_favorite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='itinerary',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
