# Generated by Django 6.0.1 on 2026-08-27 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_trip_end_date_alter_trip_itinerary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='origin',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
